@startuml
title "Sanus Bank 계좌 이체"
left to right direction
skinparam packageStyle rectangle

actor "customer"
actor "employee"
actor "system admin"

package sanus_bank {
    usecase "계좌 이체" as UC1
    usecase "계정 인증" as UC2
    usecase "계좌 검증" as UC3
}

customer --> UC1
UC1.> UC2 : include
UC2.> UC3 : include

@enduml

